
package examen.pkg1_guillermoespinal;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Examen_main extends javax.swing.JFrame {
    
    
    public Examen_main() {
        
        
        initComponents();
        
        
        
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_libros_info.getModel();
        
        Usuario usuario = new admin("admin", "123", new Date(), 123123,"@gmail.com","Romance");
        usuarios.add(new Usuario("colaborador1", "234", new Date(), 213234321,"@gmail.com", "Fantasia"));
        usuarios.add(new Usuario("colaborador2", "567", new Date(), 324321321,"@gmail.com", "Accion"));
        usuarios.add(new Usuario("colaborador3", "789", new Date(), 2241234,"@gmail.com", "Historia"));
        usuarios.add(new Usuario("colaborador4", "123", new Date(), 21454353,"@gmail.com", "Romance"));
        // creacion de los 5 libros (faltan 2)
        Libro libro = new Libro("Alicia en el pais de las maravillas", "Lindo bonito y loco", 2, 4, "Fantasia", 350, 1, " sepa ", new Date());
        libros.add(libro);
       // dc.addElement(libro);
        //cb-libros_info
        libros.add(new Libro("Como comer para dummies ", "comida", 1,123 , "Historia", 200, 2, "Henry", new Date()));
        libros.add(new Libro("Hunger Games ", "los juegos del hambre", 4,30 , "Accion", 450, 1, "H.P Lovecraft", new Date()));
        libros.add(new Libro("Libro4 ", "libro", 4,30 , "Accion", 450, 1, "H.P Lovecraft", new Date()));
        libros.add(new Libro("Libro5 ", "libro5", 6,50 , "Romance", 450, 1, "H.P Lovecraft", new Date()));
        for (int i = 0; i < libros.size(); i++) {
            dc.addElement(libros.get(i));
        }
        
        cb_libros_info.setModel(dc);
        cb_libros_agregar.setModel(dc);
        cb_modificar.setModel(dc);
        
        
        
       /* jp_crearlibros.setVisible(false);
        jp_crearusuarios.setVisible(false);
        jp_modificar.setVisible(false);
        jp_verlibrosgenero.setVisible(false);
        jp_historial.setVisible(false);
        jp_verlibro.setVisible(false);
        jp_agregarlibro.setVisible(false);*/
        //tf_usuario.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generos_usu = new javax.swing.ButtonGroup();
        generos = new javax.swing.ButtonGroup();
        generos_mod = new javax.swing.ButtonGroup();
        jpanel_crearlibros = new javax.swing.JTabbedPane();
        jp_login = new javax.swing.JPanel();
        bt_entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jp_crearusuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rb_romanceusu = new javax.swing.JRadioButton();
        rb_accionusu = new javax.swing.JRadioButton();
        rb_historiausu = new javax.swing.JRadioButton();
        rb_fantasiausu = new javax.swing.JRadioButton();
        tf_creacion_usuario = new javax.swing.JTextField();
        tf_creacion_correo = new javax.swing.JTextField();
        tf_creacion_numero = new javax.swing.JTextField();
        tf_creacion_contra = new javax.swing.JTextField();
        jd_fecha_usu = new com.toedter.calendar.JDateChooser();
        bt_crear = new javax.swing.JButton();
        jp_crearlibros = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        tf_descripcion = new javax.swing.JTextField();
        tf_autor = new javax.swing.JTextField();
        rb_fantasia = new javax.swing.JRadioButton();
        rb_accion = new javax.swing.JRadioButton();
        rb_romance = new javax.swing.JRadioButton();
        rb_historia = new javax.swing.JRadioButton();
        jd_publicacion = new com.toedter.calendar.JDateChooser();
        spi_puntaje = new javax.swing.JSpinner();
        spi_copias = new javax.swing.JSpinner();
        spi_edicion = new javax.swing.JSpinner();
        tf_precio = new javax.swing.JTextField();
        bt_newlibro = new javax.swing.JButton();
        jp_historial = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_historial = new javax.swing.JTextArea();
        mostrar_historial = new javax.swing.JButton();
        jp_modificar = new javax.swing.JPanel();
        cb_modificar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        spi_edicion_mod = new javax.swing.JSpinner();
        spi_puntaje_mod = new javax.swing.JSpinner();
        spi_copias_mod = new javax.swing.JSpinner();
        tf_titulo_mod = new javax.swing.JTextField();
        tf_precio_mod = new javax.swing.JTextField();
        jd_publicacion_mod = new com.toedter.calendar.JDateChooser();
        rb_fantasia_mod = new javax.swing.JRadioButton();
        rb_romance_mod = new javax.swing.JRadioButton();
        rb_historia_mod = new javax.swing.JRadioButton();
        rb_accion_mod = new javax.swing.JRadioButton();
        tf_descripcion_mod = new javax.swing.JTextField();
        tf_autor_mod = new javax.swing.JTextField();
        jp_verlibrosgenero = new javax.swing.JPanel();
        jp_verlibro = new javax.swing.JPanel();
        cb_libros_info = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descrip = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_titulo1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_titulo = new javax.swing.JTextArea();
        jp_agregarlibro = new javax.swing.JPanel();
        cb_libros_agregar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_entrar.setText("Entrar");
        bt_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_entrarMouseClicked(evt);
            }
        });

        jLabel1.setText("Usuario: ");

        jLabel2.setText("Contrasena");

        javax.swing.GroupLayout jp_loginLayout = new javax.swing.GroupLayout(jp_login);
        jp_login.setLayout(jp_loginLayout);
        jp_loginLayout.setHorizontalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_loginLayout.createSequentialGroup()
                .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_loginLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(bt_entrar)))
                    .addGroup(jp_loginLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_loginLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel2)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jp_loginLayout.setVerticalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(bt_entrar)
                .addGap(23, 23, 23))
        );

        jpanel_crearlibros.addTab("Logging", jp_login);

        jp_crearusuarios.setEnabled(false);

        jLabel3.setText("Nombre de usuario :");

        jLabel4.setText("Genero favorito: ");

        jLabel5.setText("Contrasena :");

        jLabel6.setText("Fecha de nacimiento: ");

        jLabel7.setText("Numero de telefono: ");

        jLabel8.setText("Correo :  ");

        generos_usu.add(rb_romanceusu);
        rb_romanceusu.setText("Romance");

        generos_usu.add(rb_accionusu);
        rb_accionusu.setText("Accion");

        generos_usu.add(rb_historiausu);
        rb_historiausu.setText("Historia");

        generos_usu.add(rb_fantasiausu);
        rb_fantasiausu.setText("Fantasia");

        bt_crear.setText("crear usuario");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_crearusuariosLayout = new javax.swing.GroupLayout(jp_crearusuarios);
        jp_crearusuarios.setLayout(jp_crearusuariosLayout);
        jp_crearusuariosLayout.setHorizontalGroup(
            jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearusuariosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                        .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_creacion_contra)
                                .addGap(146, 146, 146))
                            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jd_fecha_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                        .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(313, 313, 313))
                            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rb_romanceusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rb_historiausu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_fantasiausu)
                                    .addComponent(rb_accionusu))
                                .addGap(205, 205, 205))))
                    .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                        .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_creacion_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_creacion_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193)
                                .addComponent(bt_crear)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(tf_creacion_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );
        jp_crearusuariosLayout.setVerticalGroup(
            jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_creacion_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_creacion_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_romanceusu)
                        .addComponent(rb_accionusu)))
                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_fantasiausu)
                            .addComponent(rb_historiausu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jd_fecha_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearusuariosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_creacion_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearusuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(jp_crearusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearusuariosLayout.createSequentialGroup()
                    .addContainerGap(261, Short.MAX_VALUE)
                    .addComponent(tf_creacion_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(124, 124, 124)))
        );

        jpanel_crearlibros.addTab("Crear usuario", jp_crearusuarios);

        jp_crearlibros.setEnabled(false);

        jLabel9.setText("Titulo: ");

        jLabel10.setText("descripcion :");

        jLabel11.setText("copias :");

        jLabel12.setText("genero: ");

        jLabel13.setText("puntaje :");

        jLabel14.setText("valor :");

        jLabel15.setText("autor :");

        jLabel16.setText("fecha de publicacion :");

        jLabel17.setText("edicion: ");

        generos.add(rb_fantasia);
        rb_fantasia.setText("Fantasia");

        generos.add(rb_accion);
        rb_accion.setText("Accion");

        generos.add(rb_romance);
        rb_romance.setText("Romance");

        generos.add(rb_historia);
        rb_historia.setText("Historia");

        spi_puntaje.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spi_puntaje.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spi_copias.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        spi_copias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spi_edicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spi_edicion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bt_newlibro.setText("crear libro");
        bt_newlibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_newlibroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_crearlibrosLayout = new javax.swing.GroupLayout(jp_crearlibros);
        jp_crearlibros.setLayout(jp_crearlibrosLayout);
        jp_crearlibrosLayout.setHorizontalGroup(
            jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spi_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_fantasia)
                                    .addComponent(rb_accion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spi_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                        .addComponent(rb_historia)
                                        .addGap(78, 78, 78)
                                        .addComponent(bt_newlibro))
                                    .addComponent(rb_romance))
                                .addGap(238, 238, 238))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spi_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jd_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearlibrosLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(201, 201, 201)))))
                    .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_descripcion))
                        .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jp_crearlibrosLayout.setVerticalGroup(
            jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spi_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(spi_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_crearlibrosLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(spi_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearlibrosLayout.createSequentialGroup()
                                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jd_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rb_fantasia)
                            .addComponent(rb_romance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_crearlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_historia)
                            .addComponent(rb_accion))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_crearlibrosLayout.createSequentialGroup()
                        .addComponent(bt_newlibro)
                        .addGap(19, 19, 19))))
        );

        jpanel_crearlibros.addTab("Crear Libros", jp_crearlibros);

        jp_historial.setEnabled(false);

        ta_historial.setColumns(20);
        ta_historial.setRows(5);
        jScrollPane4.setViewportView(ta_historial);

        mostrar_historial.setText("Mostrar");
        mostrar_historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrar_historialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_historialLayout = new javax.swing.GroupLayout(jp_historial);
        jp_historial.setLayout(jp_historialLayout);
        jp_historialLayout.setHorizontalGroup(
            jp_historialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_historialLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(mostrar_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jp_historialLayout.setVerticalGroup(
            jp_historialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_historialLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_historialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mostrar_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        jpanel_crearlibros.addTab("Historial", jp_historial);

        jp_modificar.setEnabled(false);

        jButton1.setText("Modificar el Titulo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Modificar el Genero");

        jButton3.setText("Modificar la fecha");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Modificar la Descripcion");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Modificar el Puntaje");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Modificar el valor ");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Modificar el  autor");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Modificar la Edicion");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Modificar las copias del libro");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        spi_edicion_mod.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spi_edicion_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spi_puntaje_mod.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spi_puntaje_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spi_copias_mod.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        spi_copias_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        generos_mod.add(rb_fantasia_mod);
        rb_fantasia_mod.setText("Fantasia");

        generos_mod.add(rb_romance_mod);
        rb_romance_mod.setText("Romance");

        generos_mod.add(rb_historia_mod);
        rb_historia_mod.setText("Historia");

        generos_mod.add(rb_accion_mod);
        rb_accion_mod.setText("Accion");

        javax.swing.GroupLayout jp_modificarLayout = new javax.swing.GroupLayout(jp_modificar);
        jp_modificar.setLayout(jp_modificarLayout);
        jp_modificarLayout.setHorizontalGroup(
            jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarLayout.createSequentialGroup()
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_modificarLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_modificarLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_modificarLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_modificarLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(spi_puntaje_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_modificarLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(tf_titulo_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_modificarLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(tf_precio_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addGroup(jp_modificarLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(spi_copias_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_autor_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(117, Short.MAX_VALUE))
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(rb_romance_mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_accion_mod)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modificarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tf_descripcion_mod)
                .addGap(27, 27, 27)
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addComponent(rb_fantasia_mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_historia_mod)))
                .addGap(46, 46, 46)
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modificarLayout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addGap(135, 135, 135))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modificarLayout.createSequentialGroup()
                            .addComponent(spi_edicion_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(176, 176, 176)))
                    .addComponent(jButton7)
                    .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jd_publicacion_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))))
        );
        jp_modificarLayout.setVerticalGroup(
            jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarLayout.createSequentialGroup()
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_autor_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_titulo_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jd_publicacion_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(rb_fantasia_mod)
                            .addComponent(rb_historia_mod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_romance_mod)
                            .addComponent(rb_accion_mod))
                        .addGap(139, 139, 139))
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(tf_descripcion_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spi_puntaje_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spi_edicion_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_precio_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spi_copias_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton9))
                        .addContainerGap())))
        );

        jpanel_crearlibros.addTab("Modificar libro", jp_modificar);

        jp_verlibrosgenero.setEnabled(false);

        javax.swing.GroupLayout jp_verlibrosgeneroLayout = new javax.swing.GroupLayout(jp_verlibrosgenero);
        jp_verlibrosgenero.setLayout(jp_verlibrosgeneroLayout);
        jp_verlibrosgeneroLayout.setHorizontalGroup(
            jp_verlibrosgeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        jp_verlibrosgeneroLayout.setVerticalGroup(
            jp_verlibrosgeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jpanel_crearlibros.addTab("Ver libros por genero", jp_verlibrosgenero);

        jp_verlibro.setEnabled(false);

        cb_libros_info.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_libros_infoItemStateChanged(evt);
            }
        });

        ta_descrip.setColumns(20);
        ta_descrip.setRows(5);
        jScrollPane1.setViewportView(ta_descrip);

        ta_titulo1.setColumns(20);
        ta_titulo1.setRows(5);
        jScrollPane2.setViewportView(ta_titulo1);

        ta_titulo.setColumns(20);
        ta_titulo.setRows(5);
        jScrollPane3.setViewportView(ta_titulo);

        javax.swing.GroupLayout jp_verlibroLayout = new javax.swing.GroupLayout(jp_verlibro);
        jp_verlibro.setLayout(jp_verlibroLayout);
        jp_verlibroLayout.setHorizontalGroup(
            jp_verlibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_verlibroLayout.createSequentialGroup()
                .addGroup(jp_verlibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_verlibroLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_verlibroLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jp_verlibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_libros_info, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jp_verlibroLayout.setVerticalGroup(
            jp_verlibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_verlibroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cb_libros_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jpanel_crearlibros.addTab("Ver info de libro", jp_verlibro);

        jp_agregarlibro.setEnabled(false);

        cb_libros_agregar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_libros_agregarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jp_agregarlibroLayout = new javax.swing.GroupLayout(jp_agregarlibro);
        jp_agregarlibro.setLayout(jp_agregarlibroLayout);
        jp_agregarlibroLayout.setHorizontalGroup(
            jp_agregarlibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarlibroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cb_libros_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jp_agregarlibroLayout.setVerticalGroup(
            jp_agregarlibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarlibroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cb_libros_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        jpanel_crearlibros.addTab("Agregar libros a lista", jp_agregarlibro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_crearlibros)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_crearlibros)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entrarMouseClicked
        Boolean loggin_admin =false;
        Boolean loggin_user =false;
        String usu = tf_usuario.getText();
        String pass = tf_contra.getText();
       
      
        for (int i = 0; i <usuarios.size(); i++) {
            if(usuarios.get(i)instanceof admin){
                if(usuarios.get(i).getUsuario().equals(usu)){
                    if (usuarios.get(i).getContra().equals(pass)) {
                        loggin_admin=true;
                        nombre_usuario = usuarios.get(i).getUsuario();
                        usuario.setUsuario(usuarios.get(i).getUsuario());
                       // Usuario usuario = usuario;
                    }
                }
            }else{
                if(usuarios.get(i).getUsuario().equals(usu)){
                    if (usuarios.get(i).getContra().equals(pass)) {
                        loggin_user=true;
                        nombre_usuario = usuarios.get(i).getUsuario();
                        usuario.setContra(usuarios.get(i).getUsuario());
                    }
                }
            }
        }
        
        
        
        if (loggin_admin) {
           
            //jpanel_crearlibros.setEnabled(true);
            jp_agregarlibro.setEnabled(true);
            jp_crearlibros.setEnabled(true);
            jp_crearusuarios.setEnabled(true);
            jp_historial.setEnabled(true);
            jp_login.setEnabled(true);
            jp_modificar.setEnabled(true);
            jp_verlibro.setEnabled(true);
            jp_verlibrosgenero.setEnabled(true);
            
        }else if (loggin_user){
            //jp_crearusuarios.setVisible(true);
            jp_verlibro.setEnabled(true);
            jp_verlibrosgenero.setEnabled(true);
            jp_historial.setEnabled(true);
        }else{
             jp_crearusuarios.setVisible(true);
        }
    }//GEN-LAST:event_bt_entrarMouseClicked

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        try {
        String usuario = tf_creacion_usuario.getText();
        String contra= tf_creacion_contra.getText();
        String correo = tf_creacion_correo.getText();
        int numero = Integer.parseInt(tf_creacion_numero.getText());
        Date fecha = jd_fecha_usu.getDate();
        String genero= " " ;
        if (rb_fantasiausu.isSelected()) {
            genero = "Fantasia";
        }else if(rb_historiausu.isSelected()){
            genero = "Historia";
        }else if(rb_romanceusu.isSelected()){
            genero = "Romance";
        }else if(rb_accionusu.isSelected()){
            genero = "Accion";
        }
        Usuario user = new Usuario(usuario, contra, fecha, numero, correo, genero);
        usuarios.add(user);
        historial += nombre_usuario+" a creado un usuario\n";
        //seters
        tf_creacion_usuario.setText("");
        tf_creacion_contra.setText("");
        tf_creacion_correo.setText("");
        tf_creacion_numero.setText("");
        
        rb_accionusu.setSelected(true);
        rb_romanceusu.setSelected(false);
        rb_historiausu.setSelected(false);
        rb_fantasiausu.setSelected(false);
        jd_fecha_usu.setDate(new Date());
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrio un error no se pudo crear el usuario");
            historial+= (nombre_usuario + "Ocurrio un error no se pudo crear el usuario\n");
        }
        //String 
    }//GEN-LAST:event_bt_crearMouseClicked

    private void bt_newlibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_newlibroMouseClicked
      try {
        String titulo= tf_titulo.getText();
       String descrip = tf_descripcion.getText();
       int edicion = (Integer)spi_edicion.getValue();
       int puntaje = (Integer)spi_puntaje.getValue();
       int copias= (Integer)spi_copias.getValue();
       //int edicion = (Integer)spi_edicion.getValue();
       String autor =tf_autor.getText();
       Date fecha = jd_publicacion.getDate();
       int valor = Integer.parseInt(tf_precio.getText());
       String genero= " " ;
        if (rb_fantasia.isSelected()) {
            genero = "Fantasia";
        }else if(rb_historia.isSelected()){
            genero = "Historia";
        }else if(rb_romance.isSelected()){
            genero = "Romance";
        }else if(rb_accion.isSelected()){
            genero = "Accion";
        }
        Libro libro = new Libro(titulo, descrip, puntaje, copias, genero, ERROR, edicion, autor, fecha);
        libros.add(libro);
        historial+=(nombre_usuario+" creo un libro \n");
        //cambio del modelo del combo box
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_libros_info.getModel();
        dc.addElement(libro);
        cb_libros_info.setModel(dc);
        // cambio de modelo del segundo combo box
        DefaultComboBoxModel libros_dc = (DefaultComboBoxModel) cb_libros_agregar.getModel();
        libros_dc.addElement(libro);
        cb_libros_agregar.setModel(libros_dc);
        //cambio del tercer combox
        cb_modificar.setModel(dc);
        
        
      }catch (Exception e){
          JOptionPane.showMessageDialog(this,"Ocurrio un error no se pudo crear el libro ");
          historial+=("Ocurrio un error no se pudo crear el libro \n");
      }
    }//GEN-LAST:event_bt_newlibroMouseClicked

    private void mostrar_historialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrar_historialMouseClicked
        ta_historial.setText(historial);
    }//GEN-LAST:event_mostrar_historialMouseClicked

    private void cb_libros_infoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_libros_infoItemStateChanged
        if (evt.getStateChange()==2){
            Libro libro = (Libro) cb_libros_info.getSelectedItem();
            ta_titulo.setText(libro.getTitulo());
            ta_descrip.setText(libro.toString());
        }
    }//GEN-LAST:event_cb_libros_infoItemStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cb_libros_agregarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_libros_agregarItemStateChanged
       if (evt.getStateChange()==2){
            Libro libro = (Libro) cb_libros_agregar.getSelectedItem();
            usuario.setLibro(libro);
            //ya vuelvo
          
        }
    }//GEN-LAST:event_cb_libros_agregarItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setTitulo(tf_titulo_mod.getText());
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setDescripcion(tf_descripcion_mod.getText());
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setPuntaje((int) spi_puntaje_mod.getValue());
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setValor(Integer.parseInt(tf_precio_mod.getText()));
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
       Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setCopias((int)spi_copias_mod.getValue());
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
       Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setEdicion((int)spi_edicion_mod.getValue());
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
     Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setFecha(jd_publicacion_mod.getDate());
        ///
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
       Libro libro =(Libro) cb_modificar.getSelectedItem();
        libro.setAutor(tf_autor_mod.getText());
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen_main().setVisible(true);
            }
        });
        
        
        //creacion de los usuarios administradores
       
        
        //validacion de loggin
        
            
        
        //if (usuarios.{
        
        
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_newlibro;
    private javax.swing.JComboBox<String> cb_libros_agregar;
    private javax.swing.JComboBox<String> cb_libros_info;
    private javax.swing.JComboBox<String> cb_modificar;
    private javax.swing.ButtonGroup generos;
    private javax.swing.ButtonGroup generos_mod;
    private javax.swing.ButtonGroup generos_usu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jd_fecha_usu;
    private com.toedter.calendar.JDateChooser jd_publicacion;
    private com.toedter.calendar.JDateChooser jd_publicacion_mod;
    private javax.swing.JPanel jp_agregarlibro;
    private javax.swing.JPanel jp_crearlibros;
    private javax.swing.JPanel jp_crearusuarios;
    private javax.swing.JPanel jp_historial;
    private javax.swing.JPanel jp_login;
    private javax.swing.JPanel jp_modificar;
    private javax.swing.JPanel jp_verlibro;
    private javax.swing.JPanel jp_verlibrosgenero;
    private javax.swing.JTabbedPane jpanel_crearlibros;
    private javax.swing.JButton mostrar_historial;
    private javax.swing.JRadioButton rb_accion;
    private javax.swing.JRadioButton rb_accion_mod;
    private javax.swing.JRadioButton rb_accionusu;
    private javax.swing.JRadioButton rb_fantasia;
    private javax.swing.JRadioButton rb_fantasia_mod;
    private javax.swing.JRadioButton rb_fantasiausu;
    private javax.swing.JRadioButton rb_historia;
    private javax.swing.JRadioButton rb_historia_mod;
    private javax.swing.JRadioButton rb_historiausu;
    private javax.swing.JRadioButton rb_romance;
    private javax.swing.JRadioButton rb_romance_mod;
    private javax.swing.JRadioButton rb_romanceusu;
    private javax.swing.JSpinner spi_copias;
    private javax.swing.JSpinner spi_copias_mod;
    private javax.swing.JSpinner spi_edicion;
    private javax.swing.JSpinner spi_edicion_mod;
    private javax.swing.JSpinner spi_puntaje;
    private javax.swing.JSpinner spi_puntaje_mod;
    private javax.swing.JTextArea ta_descrip;
    private javax.swing.JTextArea ta_historial;
    private javax.swing.JTextArea ta_titulo;
    private javax.swing.JTextArea ta_titulo1;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autor_mod;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_creacion_contra;
    private javax.swing.JTextField tf_creacion_correo;
    private javax.swing.JTextField tf_creacion_numero;
    private javax.swing.JTextField tf_creacion_usuario;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_descripcion_mod;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio_mod;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_titulo_mod;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Libro>libros= new ArrayList();
    static ArrayList<Usuario> usuarios = new ArrayList();
    static String historial;
    static  String nombre_usuario;
      static Usuario usuario = new Usuario();
    //Libro libro = new Libro("Alicia en el pais de las maravillas", "Lindo bonito y loco", 2, 4, "Fantasia", 350, 1, " sepa ", new Date());
    //libros.add(libro);
    
    

}
